# Generated by Django 4.1.1 on 2022-09-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='chef_name',
            field=models.CharField(choices=[('mom', 'Mom'), ('dad', 'Dad'), ('kat', 'Kat'), ('isaac', 'Isaac')], max_length=20),
        ),
    ]
