# Generated by Django 4.1.1 on 2022-09-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_alter_chef_chef_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='whos_cooking',
        ),
    ]
