# Generated by Django 4.1.1 on 2022-09-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0003_remove_meal_whos_cooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='grocery_desc',
            field=models.CharField(blank=True, help_text='Description', max_length=200),
        ),
    ]
